---
title: "The Mode Choice Models of BEAM and ActivitySim"
author:
  - name: Christopher Day
    email: christophersday@gmail.com
    affiliation: Brigham Young University
    footnote: 1
  - name: Gregory Macfarlane
    email: gregmacfarlane@byu.edu
    affiliation: Brigham Young University
    footnote: 2
address:
  - code: Brigham Young University
    address: Civil and Environmental Engineering Department, 430 Engineering Building, Provo, Utah 84602
  - code: Another University
    address: Some Other Place
footnote:
  - code: 1
    text: "Corresponding Author"
  - code: 2
    text: "Present affiliation: some nice job"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
journal: "Submitted to Journal"
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
abstract: |
  The purpose of this exploration is to understand in detail the mode choice processes in BEAM as well as the mode choice process in ActivitySim. After a deep understanding is acheived, the next goal will be to align BEAM's current mode choice process with ActivitySim's. By updating BEAM's mode choice process, the outputs generated by BEAM will be more meaningful and in line with the inputs given by ActivitySim.  
  
  In Beam, two mode choice processes exist: the multinomial logit choice model and the latent class choice model. First the theory behind the two choice models as well as utility theory is explained. Then, the specifics of how the multinomial mode choice model and the latent class mode choice model work in BEAM's code is explained. Afterwards, the specifics of how ActivitySim's mode choice is organized is explained. A comparison will be given between the mode choice parameters given by an analysis done in SLC in ActivtySim and BEAM's default values. Finally, a proposal to align BEAM's mode choice model with ActivitySim's is given. More specifically, the idea is to implement mode choice decisions based on purpose within BEAM. 

description: "A short description"
layout: "3p, authoryear"
keywords:
  - Accessibility
  - Passive Data
  - Location Choice
---

# Introduction {#intro}

The most prominent behavior in BEAM is mode choice. Since BEAM is an adaptive microsimulation modeling tool, the mode choice in BEAM is also adaptive. Yes, mode choice can be specified in the plans file, but after the 0 iteration, the adaptive process takes place.

The following modes are considered as options in BEAM:

  - walk
  - car
  - bike
  - ride_hail
  - ride_hail_pooled
  - walk_transit
  - drive_transit
  - bike_transit
  - ride_hail_transit
  
The mode options are displayed in the correct format for usage in BEAM. Also,  walk is the fallback modal option if for some reason the planned mode becomes impossible within the framework. 

There are two mode choice models set up within BEAM to adaptively select modes for each user based on default parameters. The first one is the multinomial logit mode choice model. The second one is the latent class mode choice model. These two mode choice models will be explained thoroughly in Chapter \@ref(chap3).
  
Following the explanation of the mode choice models in BEAM, Chapter \@ref(chap4) dives into the mode choice model in ActivitySim, and proposes why implementing a purpose based mode choice model in BEAM could prove beneficial. It also shows a comparison between the mode choice parameters from ActivitySim and BEAM to further prove why it is beneficial. 

Additional information about BEAM's mode choice can be found in the user guide at [https://beam.readthedocs.io/en/latest/behaviors.html#mode-choice](https://beam.readthedocs.io/en/latest/behaviors.html#mode-choice).

Information about ActivitySim's mode choice can be found the Calibration and Validation of the model at [http://analytics.mtc.ca.gov/foswiki/pub/Main/Documents/2012_05_18_RELEASE_DRAFT_Calibration_and_Validation.pdf].
